# -*- coding: utf-8 -*-
"""
/***************************************************************************
 grain_checker
                                 A QGIS plugin
 grain size sensitivity test
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-26
        copyright            : (C) 2026 by Rintozxr
        email                : xinranzhang0520@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load grain_checker class from file grain_checker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .grain_checker import grain_checker
    return grain_checker(iface)
