# -*- coding: utf-8 -*-
"""
/***************************************************************************
 grain_checkerDialog
                                 A QGIS plugin
 grain size sensitivity test
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-26
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Rintozxr
        email                : xinranzhang0520@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'grain_checker_dialog_base.ui'))


class grain_checkerDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(grain_checkerDialog, self).__init__(parent)
        self.setupUi(self)

        #限定
        self.comboPointLayer.setEditable(False)
        self.comboCovariateLayer.setEditable(False)

        if not self.lineScale1.text().strip():
            self.lineScale1.setText("50")
        if not self.lineScale2.text().strip():
            self.lineScale2.setText("100")
        if not self.lineScale3.text().strip():
            self.lineScale3.setText("200")

        self.populate_point_layers()

    #输入
    def populate_point_layers(self):
        self.comboPointLayer.clear()
        self.comboCovariateLayer.clear()

        point_layers = []
        for layer in QgsProject.instance().mapLayers().values():
            if not isinstance(layer, QgsVectorLayer):
                continue
            if layer.geometryType() != QgsWkbTypes.PointGeometry:
                continue
            point_layers.append(layer)

        for layer in point_layers:
            self.comboPointLayer.addItem(layer.name(), layer)
            self.comboCovariateLayer.addItem(layer.name(), layer)

        #默认协变量
        if self.comboCovariateLayer.count() > 1:
            self.comboCovariateLayer.setCurrentIndex(1)

    def populate_fields(self):
        self.comboValueField.clear()

        layer = self.comboPointLayer.currentData()
        if layer is None:
            return

        numeric_types = {
            QVariant.Int,
            QVariant.Double,
            QVariant.LongLong,
            QVariant.UInt,
            QVariant.ULongLong,
        }

        for field in layer.fields():
            if field.type() in numeric_types:
                self.comboValueField.addItem(field.name())
