# -*- coding: utf-8 -*-
"""
/***************************************************************************
 grain_checker
                                 A QGIS plugin
 grain size sensitivity test
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-26
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Rintozxr
        email                : xinranzhang0520@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
# -*- coding: utf-8 -*-
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox

import os.path

from .resources import *
from .grain_checker_dialog import grain_checkerDialog
from .grain_runner import run_bivariate_density_stress_test, format_bivariate_result_message


class grain_checker:

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        self.actions = []
        self.menu = self.tr(u'&grain_checker')
        self.first_start = None


    def tr(self, message):
        return QCoreApplication.translate('grain_checker', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None
    ):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = ':/plugins/grain_checker/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Grain Checker'),
            callback=self.run,
            parent=self.iface.mainWindow()
        )
        self.first_start = True

    def unload(self):
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&grain_checker'), action)
            self.iface.removeToolBarIcon(action)

    def run(self):

        if self.first_start:
            self.first_start = False
            self.dlg = grain_checkerDialog()

        result = self.dlg.exec_()
        if result:

            try:
                event_layer = self.dlg.comboPointLayer.currentData()
                cov_layer = self.dlg.comboCovariateLayer.currentData()

                scales = [
                    float(self.dlg.lineScale1.text().strip()),
                    float(self.dlg.lineScale2.text().strip()),
                    float(self.dlg.lineScale3.text().strip())
                ]

                if event_layer is None:
                    QMessageBox.warning(None, "Grain-Checker", "Select event layer.")
                    return

                if cov_layer is None:
                    QMessageBox.warning(None, "Grain-Checker", "Select covariate layer.")
                    return

                out = run_bivariate_density_stress_test(
                    event_layer=event_layer,
                    cov_layer=cov_layer,
                    scales=scales,
                    add_layers_to_project=True
                )

                msg = format_bivariate_result_message(out)
                QMessageBox.information(None, "Grain-Checker Result", msg)

            except Exception as e:
                QMessageBox.critical(None, "Grain-Checker Error", str(e))